# Generated by Django 4.2.15 on 2024-09-15 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
        ("user", "0002_rename_id_user_strip_user_id_user_stripe"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wallet.wallet",
            ),
        ),
    ]
